export declare const enum ActionType {
    ADD_CHOICE = "ADD_CHOICE",
    REMOVE_CHOICE = "REMOVE_CHOICE",
    FILTER_CHOICES = "FILTER_CHOICES",
    ACTIVATE_CHOICES = "ACTIVATE_CHOICES",
    CLEAR_CHOICES = "CLEAR_CHOICES",
    ADD_GROUP = "ADD_GROUP",
    ADD_ITEM = "ADD_ITEM",
    REMOVE_ITEM = "REMOVE_ITEM",
    HIGHLIGHT_ITEM = "HIGHLIGHT_ITEM",
    CLEAR_ALL = "CLEAR_ALL",
    SET_IS_LOADING = "SET_IS_LOADING"
}
